### ISSUE TITLE
To list files that you want to skip

### ISSUE THREAD

**Issue by tido-** [an1muscr33d/kde-plasma-backup#4]
Hi Ruben,

First of all, Thank you very much for the script.
So many write about it, but you created an easy solution. Brilliant.

As I have adjusted also the file: user-places.xbel (dolphin),  I looked into the code why this has not been copied and found this section. 
In the script:
SHARE_FILES=
CONFIG_FILES=
https://github.com/rubenaleman/kde-plasma-backup/blob/b891ccc5abfc503bd27c3314aa4d67c88666e873/kde-plasma-backup.sh#L11-L12

---
These two lines look to me like a small workaround:
    rsync -aqR ${HOME}/./.config/k* $BACKUP_DIR
    rsync -aqR ${HOME}/./.gtkrc-2.0 $BACKUP_DIR

The backup section:
https://github.com/rubenaleman/kde-plasma-backup/blob/b891ccc5abfc503bd27c3314aa4d67c88666e873/kde-plasma-backup.sh#L57-L71

---
That said, I thought why not writing a another script where you use 
SHARE_FILES=
CONFIG_FILES=
to list files that you want to skip, like *.bak *.old , but everything else gets copied?

What were your intention to do it the way you did?

Br,
Tido

**Comment by rubenaleman** [comment]
Hi Tido,

Basically the reason was to avoid backuping more files than needed or expected inside $HOME, as the list of files to exclude would be really huge if the backup is intendeed to only backup Plasma files.

It's true that it not includes all the files from Plasma installation, but these were the ones needed from me at the moment, so because that is flexible to include any other one needed in addition.

Regards
